### PR TITLE
feat: initial commit

### PR DESCRIPTION
**Pull request by Sidor4ik**
...

### CODE REVIEW

**Comment by Sidor4ik** [comment]
Okey

**Comment by mcnic** [comment]
ok, no problem

**Comment by mcnic** [comment]
Greetings. Are you going to do anything else with this code?

**Comment by Sidor4ik** [comment]
Hello. Yes, i have implemented 2 func (copy/create). And i would like to complete FS module.

**Comment by mcnic** [comment]
You can see examples in answers of other people in [.](https://github.com/AlreadyBored/node-nodejs-basics/pulls)
It's project for learning, not grade)

**Comment by Sidor4ik** [comment]
> You can see examples in answers of other people in [PR](https://github.com/AlreadyBored/node-nodejs-basics/pulls) It's project for learning, not grade) Will you have time before the weekend, or is there only time for classes on the weekend?


I will finalize my implementation on Friday evening. I don't use their code/implementation, because it's a trap :)
I must check only my skills. You accurately noticed, that project about new knowledge.

**Pull request merged**
